server.servlet.context-path=/workintech
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_api
spring.datasource.username=postgres
spring.datasource.password=4870076
spring.jpa.hibernate.ddl-auto=update